In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from collections import defaultdict

In [2]:
df_trips = pd.read_csv("data/trips.txt")
df_routes = pd.read_csv("data/routes.txt")
df_stops = pd.read_csv("data/stops.txt")
df_stop_times = pd.read_csv("data/stop_times.txt")
df_pathways = pd.read_csv("data/pathways.txt")

# Egy megállóból elérhető szomszédok keresése

## Járatok

In [3]:
df_trips.head(5)

,route_id,trip_id,service_id,trip_headsign,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,8140,C0418310,C04183AHPMAA-011,"Soroksár, Molnár-sziget",0,C04183_8140_1_5,Y701,1.0,1.0
1,8140,C0418311,C04183AHPMAA-011,Csepel-Királyerdő,1,C04183_8140_1_6,Y702,1.0,1.0
2,8140,C0418312,C04183AHPMAA-011,"Soroksár, Molnár-sziget",0,C04183_8140_1_7,Y701,1.0,1.0
3,8140,C0418313,C04183AHPMAA-011,Csepel-Királyerdő,1,C04183_8140_1_8,Y702,1.0,1.0
4,8140,C0418314,C04183AHPMAA-011,"Soroksár, Molnár-sziget",0,C04183_8140_1_9,Y701,1.0,1.0

## Melyik járat, melyik megállóban mikor áll meg?

In [4]:
df_stop_times.head(5)

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,C0418310,F04181,08:03:00,08:03:00,0,NaN,NaN,NaN,0.0
1,C0418310,F04526,08:06:00,08:06:00,1,NaN,NaN,NaN,160.0
2,C0418311,F04526,08:30:00,08:30:00,0,NaN,NaN,NaN,0.0
3,C0418311,F04181,08:33:00,08:33:00,1,NaN,NaN,NaN,160.0
4,C0418312,F04181,08:33:00,08:33:00,0,NaN,NaN,NaN,0.0

## Most a string arrival_time-ből csináljunk számokat
Mert igy jóval gyorsabb lesz a lekérdezés

In [5]:
def str_time_to_min(astr):
    [h,m,s]=astr.split(':')
    return int(h)*60+int(m)

In [6]:
df_stop_times["arrival_time_min"]=df_stop_times["arrival_time"].apply(str_time_to_min)
df_stop_times["departure_time_min"]=df_stop_times["departure_time"].apply(str_time_to_min)

df_stop_times[["trip_id","stop_id","arrival_time","stop_sequence","arrival_time_min","departure_time_min"]].head(5)

,trip_id,stop_id,arrival_time,stop_sequence,arrival_time_min,departure_time_min
0,C0418310,F04181,08:03:00,0,483,483
1,C0418310,F04526,08:06:00,1,486,486
2,C0418311,F04526,08:30:00,0,510,510
3,C0418311,F04181,08:33:00,1,513,513
4,C0418312,F04181,08:33:00,0,513,513

Mennyi ideig kell sétálni?

In [7]:
def getminutestowalk(dst,walkspeed=3.5):
    # km/h to m / minutes
    walkspeed = walkspeed * 1000/60
    return dst / walkspeed

In [8]:
getminutestowalk(1000)

17.142857142857142

## Adott megállóban melyik járatok állnak meg X időpont után

"008152", # Mester utca / könyveskalman
"008163" # Újpest Városkapu
"F00191", # Margit híd, budai hídfő H
"F01083" # Király utca / Erzsébet körút
"F01755", # Örs vezér tere M+H'
"F01083" #  Oktogon M
"F02268", # KFKI
"009019" # Gödöllő

In [31]:
#stop_id = "F00191"
stop_id = "F00189"
arrival_time_min=str_time_to_min("9:01:00")
arrival_time_min

541

In [10]:
a=df_stops.query(f'stop_id == "{stop_id}"')["stop_name"]
stop_name=a.values[0]
stop_name

'Margit híd, budai hídfő H'

In [11]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time_min > {arrival_time_min}'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time_min"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name
df_megallo_jaratok[["stop_id","stop_name","trip_id", "route_id","arrival_time", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,arrival_time,stop_headsign,stop_sequence
0,F00189,"Margit híd, budai hídfő H",D015152828,3060,09:02:00,Móricz Zsigmond körtér M,3
4869,F00189,"Margit híd, budai hídfő H",D0576811919,2910,09:03:00,Nyugati pályaudvar M,19
4048,F00189,"Margit híd, budai hídfő H",D056221750,3040,09:03:00,Újbuda-központ M,3
6194,F00189,"Margit híd, budai hídfő H",D063983539,0910,09:04:00,Nyugati pályaudvar M,18
6199,F00189,"Margit híd, budai hídfő H",D063983573,1910,09:12:00,Nyugati pályaudvar M,8

In [12]:
df_megallo_jaratok2 = pd.merge( df_megallo_jaratok, df_routes, left_on="route_id", right_on="route_id")
df_megallo_jaratok2[["stop_id","stop_name","trip_id", "route_id","route_short_name", "arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,route_short_name,arrival_time,arrival_time_min,stop_headsign,stop_sequence
0,F00189,"Margit híd, budai hídfő H",D015152828,3060,6,09:02:00,542,Móricz Zsigmond körtér M,3
1,F00189,"Margit híd, budai hídfő H",D0576811919,2910,291,09:03:00,543,Nyugati pályaudvar M,19
2,F00189,"Margit híd, budai hídfő H",D056221750,3040,4,09:03:00,543,Újbuda-központ M,3
3,F00189,"Margit híd, budai hídfő H",D063983539,0910,91,09:04:00,544,Nyugati pályaudvar M,18
4,F00189,"Margit híd, budai hídfő H",D063983573,1910,191,09:12:00,552,Nyugati pályaudvar M,8

## Kezdjük el keresi a megálló szomszédait

### stop_times mintha erre lenne kitalálva, mert valójában egy trip későbbi megállóit keresem!

In [16]:
#trip_id="D063983577"
trip_id = "D015152828"
arrival_time_min = 541

In [17]:
df_stop_times.query(f'trip_id == "{trip_id}" and arrival_time_min > {arrival_time_min}')

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min,departure_time_min
1430663,D015152828,F00189,09:02:00,09:02:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,542,542
1430664,D015152828,F00142,09:03:00,09:03:00,4,Móricz Zsigmond körtér M,NaN,NaN,1863.0,543,543
1430665,D015152828,F00926,09:05:00,09:05:00,5,Móricz Zsigmond körtér M,NaN,NaN,2247.0,545,545
1430666,D015152828,F00935,09:07:00,09:07:00,6,Móricz Zsigmond körtér M,NaN,NaN,2935.0,547,547
1430667,D015152828,F01081,09:09:00,09:09:00,7,Móricz Zsigmond körtér M,NaN,NaN,3613.0,549,549
1430668,D015152828,F01037,09:10:00,09:10:00,8,Móricz Zsigmond körtér M,NaN,NaN,4017.0,550,550
1430669,D015152828,F01112,09:11:00,09:11:00,9,Móricz Zsigmond körtér M,NaN,NaN,4422.0,551,551
1430670,D015152828,F01169,09:13:00,09:13:00,10,Móricz Zsigmond körtér M,NaN,NaN,4847.0,553,553
1430671,D015152828,F01201,09:14:00,09:14:00,11,Móricz Zsigmond körtér M,NaN,NaN,5283.0,554,554
1430672,D015152828,F01197,09:16:00,09:16:00,12,Móricz Zsigmond körtér M,NaN,NaN,5603.0,556,556
1430673,D015152828,F01194,09:17:00,09:17:00,13,Móricz Zsigmond körtér M,NaN,NaN,5985.0,557,557
1430674,D015152828,F01378,09:19:00,09:19:00,14,Móricz Zsigmond körtér M,NaN,NaN,6453.0,559,559
1430675,D015152828,F01373,09:20:00,09:20:00,15,Móricz Zsigmond körtér M,NaN,NaN,6758.0,560,560
1430676,D015152828,F02224,09:22:00,09:22:00,16,Móricz Zsigmond körtér M,NaN,NaN,7418.0,562,562
1430677,D015152828,F02154,09:24:00,09:24:00,17,Móricz Zsigmond körtér M,NaN,NaN,7896.0,564,564
1430678,D015152828,009220,09:26:00,09:26:00,18,Móricz Zsigmond körtér M,NaN,NaN,8317.0,566,566

# Járattal elérhető szomszédok meghatározása

Először valamilyen ciklusra gondoltam, de az inner join sokkal jobb

Előről kezdem és megpróbálom a részfolyamatokat összeilleszteni

In [19]:
stop_id = "F01034"
stop_id = "F00191"
stop_id = "F00189"
arrival_time_min=str_time_to_min("9:01:00")
arrival_time_min

541

In [20]:
a=df_stops.query(f'stop_id == "{stop_id}"')["stop_name"]
stop_name=a.values[0]
stop_name

'Margit híd, budai hídfő H'

Melyik járatok állnak meg itt X időpont után:

In [21]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time_min > {arrival_time_min}'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time_min"])
df_megallo_jaratok

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min,departure_time_min,route_id,service_id,trip_headsign,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,D015152828,F00189,09:02:00,09:02:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,542,542,3060,D01515ASZWA-0011,Móricz Zs. körtér M,0,D01515_3040_99_13,B693,1.0,2.0
5822,D060313392,F00189,09:02:00,09:02:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,542,542,3060,D06031RAAPPWA-0011,Móricz Zs. körtér M,0,D06031_3040_44_8,B693,1.0,2.0
4344,D056623392,F00189,09:02:00,09:02:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,542,542,3060,D05662RAAHCWA-0011,Móricz Zs. körtér M,0,D05662_3040_44_8,B693,1.0,2.0
5317,D057823392,F00189,09:02:00,09:02:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,542,542,3060,D05782RAAHCWA-0011,Móricz Zs. körtér M,0,D05782_3040_44_8,B693,1.0,2.0
1417,D028593392,F00189,09:02:00,09:02:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,542,542,3060,D02859REHHWA-0011,Móricz Zs. körtér M,0,D02859_3040_44_8,B693,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,D01560156155,F00189,25:43:00,25:43:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,1543,1543,3060,D01560APPWA-0011,Móricz Zs. körtér M,0,D01560_3040_33_31,B693,1.0,2.0
163,D0151547396,F00189,25:43:00,25:43:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,1543,1543,3060,D01515ASZWA-0011,Móricz Zs. körtér M,0,D01515_3040_37_31,B693,1.0,2.0
2494,D0421163707,F00189,25:43:00,25:43:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,1543,1543,3060,D04211RKEPPWA-0011,Móricz Zs. körtér M,0,D04211_3040_33_31,B693,1.0,2.0
2779,D0432345823,F00189,25:43:00,25:43:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,1543,1543,3060,D04323RAAVVWA-0011,Móricz Zs. körtér M,0,D04323_3040_36_27,B693,1.0,2.0
4046,D0562157994,F00189,25:43:00,25:43:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,1543,1543,3060,D05621RAASZWA-0011,Móricz Zs. körtér M,0,D05621_3040_39_31,B693,1.0,2.0

In [22]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time_min > {arrival_time_min}'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time_min"]).drop_duplicates("route_id")

In [23]:
df_megallo_jaratok

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min,departure_time_min,route_id,service_id,trip_headsign,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,D015152828,F00189,09:02:00,09:02:00,3,Móricz Zsigmond körtér M,NaN,NaN,1441.0,542,542,3060,D01515ASZWA-0011,Móricz Zs. körtér M,0,D01515_3040_99_13,B693,1.0,2.0
4869,D0576811919,F00189,09:03:00,09:03:00,19,Nyugati pályaudvar M,NaN,NaN,6674.0,543,543,2910,D05768AHCJOP-011,Nyugati pályaudvar M,1,D05768_0910_7_7,CZ62,1.0,2.0
4048,D056221750,F00189,09:03:00,09:03:00,3,Újbuda-központ M,NaN,NaN,1441.0,543,543,3040,D05622RAAVVWA-0011,Újbuda-központ M,0,D05622_3040_10_2,0977,1.0,2.0
6194,D063983539,F00189,09:04:00,09:04:00,18,Nyugati pályaudvar M,NaN,NaN,6548.0,544,544,0910,D06398RAAVVRR-0011,Nyugati pályaudvar M,1,D06398_0910_6_2,RA93,1.0,2.0
6199,D063983573,F00189,09:12:00,09:12:00,8,Nyugati pályaudvar M,NaN,NaN,2712.0,552,552,1910,D06398RAAVVRR-0011,Nyugati pályaudvar M,1,D06398_0910_9_3,ZC98,1.0,2.0

In [24]:
#df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name
df_megallo_jaratok[["stop_id","stop_name","trip_id", "route_id","arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
0,F00189,"Margit híd, budai hídfő H",D015152828,3060,09:02:00,542,Móricz Zsigmond körtér M,3
4869,F00189,"Margit híd, budai hídfő H",D0576811919,2910,09:03:00,543,Nyugati pályaudvar M,19
4048,F00189,"Margit híd, budai hídfő H",D056221750,3040,09:03:00,543,Újbuda-központ M,3
6194,F00189,"Margit híd, budai hídfő H",D063983539,0910,09:04:00,544,Nyugati pályaudvar M,18
6199,F00189,"Margit híd, budai hídfő H",D063983573,1910,09:12:00,552,Nyugati pályaudvar M,8

Kozmetika, hogy legyen járatszám amit értek is

In [25]:
df_megallo_jaratok2 = pd.merge( df_megallo_jaratok, df_routes[["route_id","route_short_name"]], left_on="route_id", right_on="route_id")
df_megallo_jaratok2[["stop_id","stop_name","trip_id", "route_id","route_short_name", "arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,route_short_name,arrival_time,arrival_time_min,stop_headsign,stop_sequence
0,F00189,"Margit híd, budai hídfő H",D015152828,3060,6,09:02:00,542,Móricz Zsigmond körtér M,3
1,F00189,"Margit híd, budai hídfő H",D0576811919,2910,291,09:03:00,543,Nyugati pályaudvar M,19
2,F00189,"Margit híd, budai hídfő H",D056221750,3040,4,09:03:00,543,Újbuda-központ M,3
3,F00189,"Margit híd, budai hídfő H",D063983539,0910,91,09:04:00,544,Nyugati pályaudvar M,18
4,F00189,"Margit híd, budai hídfő H",D063983573,1910,191,09:12:00,552,Nyugati pályaudvar M,8

### Szomszédokat egy left join-nal fogok keresni

In [26]:
df_szomszedok = pd.merge( df_megallo_jaratok2, df_stop_times[["trip_id","stop_id","arrival_time_min","arrival_time","departure_time","departure_time_min"]], how="left", left_on="trip_id", right_on="trip_id")
df_szomszedok.columns

Index(['trip_id', 'stop_id_x', 'arrival_time_x', 'departure_time_x',
       'stop_sequence', 'stop_headsign', 'pickup_type', 'drop_off_type',
       'shape_dist_traveled', 'arrival_time_min_x', 'departure_time_min_x',
       'route_id', 'service_id', 'trip_headsign', 'direction_id', 'block_id',
       'shape_id', 'wheelchair_accessible', 'bikes_allowed', 'stop_name',
       'route_short_name', 'stop_id_y', 'arrival_time_min_y', 'arrival_time_y',
       'departure_time_y', 'departure_time_min_y'],
      dtype='object')

Túl korai járatokat törlöm

In [27]:
df_szomszedok.rename(columns={"stop_name": "stop_name_x", "arrival_time_y":"arrival_time", "arrival_time_min_y":"arrival_time_min", "stop_id_y": "stop_id", }, inplace=True)

In [33]:
indices_to_drop = df_szomszedok [ df_szomszedok["arrival_time_min"] <= arrival_time_min ].index
df_szomszedok.drop( indices_to_drop, inplace= True)

Saját magamat sem akarom látni mint szomszédot

In [34]:
indices_to_drop = df_szomszedok [ df_szomszedok["stop_id_x"] == df_szomszedok["stop_id"] ].index
df_szomszedok.drop( indices_to_drop, inplace= True)

In [35]:
df_szomszedok[["trip_id","stop_id_x","arrival_time_x","stop_name_x","stop_id","arrival_time_min"]]

,trip_id,stop_id_x,arrival_time_x,stop_name_x,stop_id,arrival_time_min
4,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F00142,543
5,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F00926,545
6,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F00935,547
7,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01081,549
8,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01037,550
9,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01112,551
10,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01169,553
11,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01201,554
12,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01197,556
13,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01194,557
14,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01378,559
15,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F01373,560
16,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F02224,562
17,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",F02154,564
18,D015152828,F00189,09:02:00,"Margit híd, budai hídfő H",009220,566
39,D0576811919,F00189,09:03:00,"Margit híd, budai hídfő H",F00930,546
40,D0576811919,F00189,09:03:00,"Margit híd, budai hídfő H",F01025,549
45,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F00142,544
46,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F00926,546
47,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F00935,548
48,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01081,550
49,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01037,551
50,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01112,552
51,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01169,554
52,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01201,555
53,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01197,557
54,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01194,558
55,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01378,560
56,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01373,561
57,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F02224,563
58,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01989,565
59,D056221750,F00189,09:03:00,"Margit híd, budai hídfő H",F01998,567
77,D063983539,F00189,09:04:00,"Margit híd, budai hídfő H",F00232,542
79,D063983539,F00189,09:04:00,"Margit híd, budai hídfő H",F00930,546
80,D063983539,F00189,09:04:00,"Margit híd, budai hídfő H",F01025,548
81,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",049903,542
82,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00227,543
83,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00226,544
84,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00225,545
85,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00224,547
86,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00229,548
87,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00231,549
88,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00232,550
90,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F00930,554
91,D063983573,F00189,09:12:00,"Margit híd, budai hídfő H",F01025,556

In [205]:
df_szomszedok2 = pd.merge(df_szomszedok, df_stops[["stop_id","stop_name","stop_lat","stop_lon"]], how = "left", left_on="stop_id", right_on="stop_id")
df_szomszedok2.columns

Index(['trip_id', 'stop_id_x', 'arrival_time_x', 'departure_time_x',
       'stop_sequence', 'stop_headsign', 'pickup_type', 'drop_off_type',
       'shape_dist_traveled', 'arrival_time_min_x', 'departure_time_min_x',
       'route_id', 'service_id', 'trip_headsign', 'direction_id', 'block_id',
       'shape_id', 'wheelchair_accessible', 'bikes_allowed', 'stop_name_x',
       'route_short_name', 'stop_id', 'arrival_time_min', 'arrival_time',
       'departure_time_y', 'departure_time_min_y', 'stop_name', 'stop_lat',
       'stop_lon'],
      dtype='object')

In [206]:
df_szomszedok2[["trip_id","route_short_name", "stop_id_x","stop_name_x","arrival_time_x","stop_id", "stop_name", "arrival_time","stop_lon","stop_lat"]]

,trip_id,route_short_name,stop_id_x,stop_name_x,arrival_time_x,stop_id,stop_name,arrival_time,stop_lon,stop_lat
0,D0592567,78,F01034,Király utca / Erzsébet körút,09:02:00,F01034,Király utca / Erzsébet körút,09:02:00,19.065950,47.503573
1,D0592567,78,F01034,Király utca / Erzsébet körút,09:02:00,F01033,Akácfa utca,09:03:00,19.062963,47.502152
2,D0592567,78,F01034,Király utca / Erzsébet körút,09:02:00,F01075,Opera M,09:04:00,19.060918,47.503158
3,D0592567,78,F01034,Király utca / Erzsébet körút,09:02:00,009025,Zichy Jenő utca,09:06:00,19.057853,47.505192
4,D0592567,78,F01034,Király utca / Erzsébet körút,09:02:00,F00938,Báthory utca / Bajcsy-Zsilinszky út,09:08:00,19.054270,47.507063
5,D0592567,78,F01034,Király utca / Erzsébet körút,09:02:00,F00970,Kossuth Lajos tér M,09:10:00,19.050925,47.505966
6,D059411951,70,F01034,Király utca / Erzsébet körút,09:02:00,F01041,Izabella utca / Király utca,09:01:00,19.069083,47.505425
7,D059411951,70,F01034,Király utca / Erzsébet körút,09:02:00,F01034,Király utca / Erzsébet körút,09:02:00,19.065950,47.503573
8,D059411951,70,F01034,Király utca / Erzsébet körút,09:02:00,F01033,Akácfa utca,09:03:00,19.062963,47.502152
9,D059411951,70,F01034,Király utca / Erzsébet körút,09:02:00,F01075,Opera M,09:04:00,19.060918,47.503158
10,D059411951,70,F01034,Király utca / Erzsébet körút,09:02:00,009025,Zichy Jenő utca,09:06:00,19.057853,47.505192
11,D059411951,70,F01034,Király utca / Erzsébet körút,09:02:00,F00938,Báthory utca / Bajcsy-Zsilinszky út,09:08:00,19.054270,47.507063
12,D059411951,70,F01034,Király utca / Erzsébet körút,09:02:00,F00970,Kossuth Lajos tér M,09:10:00,19.050925,47.505966

In [98]:
df_szomszedok2[["stop_id", "trip_id", "route_short_name", "stop_name", "arrival_time","stop_lon","stop_lat"]].values

array([['F01186', 'C96610211', '72', ..., '09:46:00', 19.089937,
        47.489434],
       ['F01223', 'C96610211', '72', ..., '09:47:00', 19.085146,
        47.48889],
       ['F01176', 'C96610211', '72', ..., '09:48:00', 19.079639,
        47.489278],
       ...,
       ['F00724', 'D046181222', '914', ..., '24:59:00', 19.120265,
        47.593141],
       ['F00907', 'D046181222', '914', ..., '25:00:00', 19.121292,
        47.595848],
       ['F00722', 'D046181222', '914', ..., '25:01:00', 19.121269,
        47.598483]], shape=(171, 7), dtype=object)

In [207]:
#retdict = defaultdict(list)
retdict=df_szomszedok2[["stop_id", "trip_id", "route_short_name", "stop_name", "arrival_time_min","stop_lon","stop_lat"]].to_dict('records')
retdict

[{'stop_id': 'F01034',
  'trip_id': 'D0592567',
  'route_short_name': '78',
  'stop_name': 'Király utca / Erzsébet körút',
  'arrival_time_min': 542,
  'stop_lon': 19.06595,
  'stop_lat': 47.503573},
 {'stop_id': 'F01033',
  'trip_id': 'D0592567',
  'route_short_name': '78',
  'stop_name': 'Akácfa utca',
  'arrival_time_min': 543,
  'stop_lon': 19.062963,
  'stop_lat': 47.502152},
 {'stop_id': 'F01075',
  'trip_id': 'D0592567',
  'route_short_name': '78',
  'stop_name': 'Opera M',
  'arrival_time_min': 544,
  'stop_lon': 19.060918,
  'stop_lat': 47.503158},
 {'stop_id': '009025',
  'trip_id': 'D0592567',
  'route_short_name': '78',
  'stop_name': 'Zichy Jenő utca',
  'arrival_time_min': 546,
  'stop_lon': 19.057853,
  'stop_lat': 47.505192},
 {'stop_id': 'F00938',
  'trip_id': 'D0592567',
  'route_short_name': '78',
  'stop_name': 'Báthory utca / Bajcsy-Zsilinszky út',
  'arrival_time_min': 548,
  'stop_lon': 19.05427,
  'stop_lat': 47.507063},
 {'stop_id': 'F00970',
  'trip_id': 'D0592567',
  'route_short_name': '78',
  'stop_name': 'Kossuth Lajos tér M',
  'arrival_time_min': 550,
  'stop_lon': 19.050925,
  'stop_lat': 47.505966},
 {'stop_id': 'F01041',
  'trip_id': 'D059411951',
  'route_short_name': '70',
  'stop_name': 'Izabella utca / Király utca',
  'arrival_time_min': 541,
  'stop_lon': 19.069083,
  'stop_lat': 47.505425},
 {'stop_id': 'F01034',
  'trip_id': 'D059411951',
  'route_short_name': '70',
  'stop_name': 'Király utca / Erzsébet körút',
  'arrival_time_min': 542,
  'stop_lon': 19.06595,
  'stop_lat': 47.503573},
 {'stop_id': 'F01033',
  'trip_id': 'D059411951',
  'route_short_name': '70',
  'stop_name': 'Akácfa utca',
  'arrival_time_min': 543,
  'stop_lon': 19.062963,
  'stop_lat': 47.502152},
 {'stop_id': 'F01075',
  'trip_id': 'D059411951',
  'route_short_name': '70',
  'stop_name': 'Opera M',
  'arrival_time_min': 544,
  'stop_lon': 19.060918,
  'stop_lat': 47.503158},
 {'stop_id': '009025',
  'trip_id': 'D059411951',
  'route_short_name': '70',
  'stop_name': 'Zichy Jenő utca',
  'arrival_time_min': 546,
  'stop_lon': 19.057853,
  'stop_lat': 47.505192},
 {'stop_id': 'F00938',
  'trip_id': 'D059411951',
  'route_short_name': '70',
  'stop_name': 'Báthory utca / Bajcsy-Zsilinszky út',
  'arrival_time_min': 548,
  'stop_lon': 19.05427,
  'stop_lat': 47.507063},
 {'stop_id': 'F00970',
  'trip_id': 'D059411951',
  'route_short_name': '70',
  'stop_name': 'Kossuth Lajos tér M',
  'arrival_time_min': 550,
  'stop_lon': 19.050925,
  'stop_lat': 47.505966}]

## Keressük meg egy útvonalon a megállók neveit

Megoldási terv: Keresek egy routet-t és az első trip-et benne.

Ahhoz a triphez lekérdezzük a megállókat.
Utána majd mellétesszük a neveket is

In [68]:
df_trips.groupby(["route_id"]).agg({"route_id":"first","trip_id":"first", "trip_headsign":"first"})

         route_id     trip_id              trip_headsign
route_id
0050         0050    D0166810               Pasaréti tér
0070         0070   D06142101    Újpalota, Nyírpalota út
0075         0075    D0172110          Blaha Lujza tér M
0078         0078     C755691    Újpalota, Nyírpalota út
0085         0085    D0166110   Kelenföld vasútállomás M
...           ...         ...                        ...
VP41         VP41  D056341087      Kamaraerdei Ifj. Park
VP50         VP50     D064891  Pestszentlőrinc, Béke tér
VP52         VP52     D048871  P.erzsébet, Pacsirtatelep
VP60         VP60     C937781             Széchenyi-hegy
VP601       VP601     D063421                Pethényi út

[376 rows x 3 columns]

### Melyik megállókban áll meg a 4-6-os ?

#### Mikor indul reggel a 4-6-os

A 3060-as járat első indulását keresem.
A groupby és agg funckiók miatt fontos

In [69]:
df_trips[ df_trips["route_id"].isin(["3060"]) ].groupby(["route_id"]).agg({"route_id":"first","trip_id":"first", "trip_headsign":"first"})["trip_id"]

route_id
3060    D015151403
Name: trip_id, dtype: object

Megvan a trip_id

In [70]:
df_stop_times[ df_stop_times["trip_id"] == "D015151066"]

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min,departure_time_min
1428865,D015151066,F01998,05:47:00,05:47:00,0,Széll Kálmán tér M,NaN,NaN,0.0,347,347
1428866,D015151066,F01992,05:49:00,05:49:00,1,Széll Kálmán tér M,NaN,NaN,544.0,349,349
1428867,D015151066,F02225,05:50:00,05:50:00,2,Széll Kálmán tér M,NaN,NaN,1087.0,350,350
1428868,D015151066,F01374,05:51:00,05:51:00,3,Széll Kálmán tér M,NaN,NaN,1750.0,351,351
1428869,D015151066,F01380,05:53:00,05:53:00,4,Széll Kálmán tér M,NaN,NaN,2073.0,353,353
1428870,D015151066,F01191,05:55:00,05:55:00,5,Széll Kálmán tér M,NaN,NaN,2395.0,355,355
1428871,D015151066,F01199,05:57:00,05:57:00,6,Széll Kálmán tér M,NaN,NaN,2948.0,357,357
1428872,D015151066,F01200,05:58:00,05:58:00,7,Széll Kálmán tér M,NaN,NaN,3233.0,358,358
1428873,D015151066,F01168,06:00:00,06:00:00,8,Széll Kálmán tér M,NaN,NaN,3677.0,360,360
1428874,D015151066,F01111,06:01:00,06:01:00,9,Széll Kálmán tér M,NaN,NaN,4109.0,361,361
1428875,D015151066,F01035,06:02:00,06:02:00,10,Széll Kálmán tér M,NaN,NaN,4511.0,362,362
1428876,D015151066,F01082,06:04:00,06:04:00,11,Széll Kálmán tér M,NaN,NaN,4914.0,364,364
1428877,D015151066,F00933,06:06:00,06:06:00,12,Széll Kálmán tér M,NaN,NaN,5596.0,366,366
1428878,D015151066,F00925,06:08:00,06:08:00,13,Széll Kálmán tér M,NaN,NaN,6287.0,368,368
1428879,D015151066,F00141,06:10:00,06:10:00,14,Széll Kálmán tér M,NaN,NaN,6764.0,370,370
1428880,D015151066,F00192,06:11:00,06:11:00,15,Széll Kálmán tér M,NaN,NaN,7096.0,371,371
1428881,D015151066,F00198,06:13:00,06:13:00,16,Széll Kálmán tér M,NaN,NaN,7841.0,373,373
1428882,D015151066,F00307,06:15:00,06:15:00,17,Széll Kálmán tér M,NaN,NaN,8311.0,375,375
1428883,D015151066,F02476,06:17:00,06:17:00,18,Széll Kálmán tér M,1.0,NaN,8529.0,377,377

### Most tegyük mellé a neveket is!

A hátsó stop_name oszlopban látszik

In [71]:
pd.merge( df_stop_times[ df_stop_times["trip_id"] == "D015151066"], df_stops, on="stop_id")

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min,departure_time_min,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding
0,D015151066,F01998,05:47:00,05:47:00,0,Széll Kálmán tér M,NaN,NaN,0.0,347,347,Újbuda-központ M,47.474042,19.046862,F01998,NaN,NaN,NaN,1.0
1,D015151066,F01992,05:49:00,05:49:00,1,Széll Kálmán tér M,NaN,NaN,544.0,349,349,Budafoki út / Szerémi sor,47.474114,19.053747,F01992,NaN,NaN,NaN,1.0
2,D015151066,F02225,05:50:00,05:50:00,2,Széll Kálmán tér M,NaN,NaN,1087.0,350,350,"Petőfi híd, budai hídfő",47.476956,19.059572,F02225,NaN,NaN,NaN,1.0
3,D015151066,F01374,05:51:00,05:51:00,3,Széll Kálmán tér M,NaN,NaN,1750.0,351,351,Boráros tér H,47.480400,19.066697,F01374,NaN,NaN,NaN,2.0
4,D015151066,F01380,05:53:00,05:53:00,4,Széll Kálmán tér M,NaN,NaN,2073.0,353,353,Mester utca / Ferenc körút,47.482775,19.068848,F01380,NaN,NaN,NaN,1.0
5,D015151066,F01191,05:55:00,05:55:00,5,Széll Kálmán tér M,NaN,NaN,2395.0,355,355,Corvin-negyed M,47.485500,19.069924,F01191,NaN,NaN,NaN,1.0
6,D015151066,F01199,05:57:00,05:57:00,6,Széll Kálmán tér M,NaN,NaN,2948.0,357,357,Harminckettesek tere,47.490357,19.070841,F01199,NaN,NaN,NaN,1.0
7,D015151066,F01200,05:58:00,05:58:00,7,Széll Kálmán tér M,NaN,NaN,3233.0,358,358,Rákóczi tér M,47.492866,19.071187,F01200,NaN,NaN,NaN,1.0
8,D015151066,F01168,06:00:00,06:00:00,8,Széll Kálmán tér M,NaN,NaN,3677.0,360,360,Blaha Lujza tér M,47.496770,19.070725,F01168,NaN,NaN,NaN,1.0
9,D015151066,F01111,06:01:00,06:01:00,9,Széll Kálmán tér M,NaN,NaN,4109.0,361,361,Wesselényi utca / Erzsébet körút,47.500350,19.068934,F01111,NaN,NaN,NaN,1.0
10,D015151066,F01035,06:02:00,06:02:00,10,Széll Kálmán tér M,NaN,NaN,4511.0,362,362,Király utca / Erzsébet körút,47.503256,19.065856,F01035,NaN,NaN,NaN,1.0
11,D015151066,F01082,06:04:00,06:04:00,11,Széll Kálmán tér M,NaN,NaN,4914.0,364,364,Oktogon M,47.505964,19.062405,F01082,NaN,NaN,NaN,1.0
12,D015151066,F00933,06:06:00,06:06:00,12,Széll Kálmán tér M,NaN,NaN,5596.0,366,366,Nyugati pályaudvar M,47.510300,19.056167,F00933,NaN,NaN,NaN,1.0
13,D015151066,F00925,06:08:00,06:08:00,13,Széll Kálmán tér M,NaN,NaN,6287.0,368,368,Jászai Mari tér,47.513116,19.048175,F00925,NaN,NaN,NaN,1.0
14,D015151066,F00141,06:10:00,06:10:00,14,Széll Kálmán tér M,NaN,NaN,6764.0,370,370,Margitsziget / Margit híd,47.514717,19.042479,F00141,NaN,NaN,NaN,1.0
15,D015151066,F00192,06:11:00,06:11:00,15,Széll Kálmán tér M,NaN,NaN,7096.0,371,371,"Margit híd, budai hídfő H",47.514653,19.038164,F00192,NaN,NaN,NaN,1.0
16,D015151066,F00198,06:13:00,06:13:00,16,Széll Kálmán tér M,NaN,NaN,7841.0,373,373,Mechwart liget,47.510767,19.031447,F00198,NaN,NaN,NaN,1.0
17,D015151066,F00307,06:15:00,06:15:00,17,Széll Kálmán tér M,NaN,NaN,8311.0,375,375,Széna tér,47.508140,19.026735,F00307,NaN,NaN,NaN,1.0
18,D015151066,F02476,06:17:00,06:17:00,18,Széll Kálmán tér M,1.0,NaN,8529.0,377,377,Széll Kálmán tér M,47.507384,19.024492,F02476,NaN,NaN,NaN,1.0

# Kódrészlet ami egy vonal megállóit keresi meg
Most egy kis kódrészlet keresi nekem az adott vonal megállóit.
Ezt lehet majd beletenni egy függvénybe

In [72]:
#route_id = "3060"
#route_id="3040"
route_id="0090"
elso_trip = df_trips[ df_trips["route_id"] == route_id ].groupby(["route_id"]).agg({"route_id":"first","trip_id":"first", "trip_headsign":"first"})["trip_id"].iloc[0]
a=pd.merge( df_stop_times[ df_stop_times["trip_id"] == elso_trip], df_stops, on="stop_id")
a["route_id"]=route_id
a[["route_id","trip_id","stop_id","stop_name","arrival_time","departure_time","stop_lat","stop_lon"]]

,route_id,trip_id,stop_id,stop_name,arrival_time,departure_time,stop_lat,stop_lon
0,0090,D033981412,F01636,Kőbánya alsó vasútállomás,04:36:00,04:36:00,47.483652,19.127839
1,0090,D033981412,F01653,Szent László tér,04:37:00,04:37:00,47.485925,19.131093
2,0090,D033981412,F01641,Liget tér,04:39:00,04:39:00,47.482795,19.130358
3,0090,D033981412,F01571,Kőbánya alsó vasútállomás (Mázsa tér),04:40:00,04:40:00,47.482879,19.125715
4,0090,D033981412,F01563,Egészségház,04:42:00,04:42:00,47.484126,19.116668
5,0090,D033981412,F01733,Eiffel Műhelyház,04:43:00,04:43:00,47.485136,19.112914
6,0090,D033981412,F01267,Kőbányai út / Könyves Kálmán körút,04:45:00,04:45:00,47.486740,19.106971
7,0090,D033981412,008036,Kőbányai út 31.,04:45:00,04:45:00,47.487461,19.104252
8,0090,D033981412,F01187,Orczy tér,04:47:00,04:48:00,47.489470,19.090495
9,0090,D033981412,F01223,Kálvária tér,04:49:00,04:49:00,47.488890,19.085146
10,0090,D033981412,F01176,Muzsikus cigányok parkja,04:50:00,04:50:00,47.489278,19.079639
11,0090,D033981412,F01207,Horváth Mihály tér,04:51:00,04:51:00,47.489594,19.076707
12,0090,D033981412,F01204,Harminckettesek tere,04:53:00,04:53:00,47.489514,19.071306
13,0090,D033981412,F01175,Szentkirályi utca,04:54:00,04:54:00,47.489191,19.066807
14,0090,D033981412,F01010,Kálvin tér M,04:56:00,04:56:00,47.490010,19.061978
15,0090,D033981412,F01013,Astoria M,04:58:00,04:58:00,47.494145,19.060146
16,0090,D033981412,009309,Deák Ferenc tér M,05:00:00,05:00:00,47.497449,19.055715
17,0090,D033981412,048506,Szent István Bazilika,05:01:00,05:01:00,47.500273,19.055025
18,0090,D033981412,F00942,Arany János utca M,05:02:00,05:02:00,47.503304,19.055105
19,0090,D033981412,F00940,Báthory utca / Bajcsy-Zsilinszky út,05:03:00,05:03:00,47.507189,19.055730
20,0090,D033981412,F01029,Nyugati pályaudvar M,05:05:00,05:06:00,47.509806,19.057151
21,0090,D033981412,F00929,Jászai Mari tér,05:08:00,05:08:00,47.512558,19.050126
22,0090,D033981412,F00237,"Margit híd, budai hídfő H",05:10:00,05:10:00,47.515518,19.038339
23,0090,D033981412,F00247,Császár-Komjádi uszoda,05:12:00,05:12:00,47.521409,19.038272
24,0090,D033981412,F00245,Zsigmond tér,05:13:00,05:13:00,47.524991,19.037951
25,0090,D033981412,F00137,Kolosy tér,05:15:00,05:15:00,47.528586,19.039001
26,0090,D033981412,F00603,Nagyszombat utca,05:16:00,05:16:00,47.531833,19.040023
27,0090,D033981412,F00604,Tímár utca,05:17:00,05:17:00,47.535152,19.039969
28,0090,D033981412,F00606,Kiscelli utca,05:18:00,05:18:00,47.538723,19.040500
29,0090,D033981412,F00611,Flórián tér,05:20:00,05:20:00,47.542896,19.042252
30,0090,D033981412,F00580,Raktár utca,05:21:00,05:21:00,47.545288,19.042837
31,0090,D033981412,F00573,"Óbuda, Bogdáni út",05:23:00,05:23:00,47.550712,19.041826

## Melyik járatok állnak meg ebben a megállóban ?

In [73]:
df_stop_times[ df_stop_times["stop_id"] == "048506"]

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min,departure_time_min
548787,C96610106,048506,07:27:00,07:27:00,9,Zugló vasútállomás,NaN,NaN,3713.0,447,447
548839,C96610111,048506,07:37:00,07:37:00,9,Zugló vasútállomás,NaN,NaN,3713.0,457,457
548889,C96610116,048506,07:44:00,07:44:00,9,Zugló vasútállomás,NaN,NaN,3713.0,464,464
548941,C96610121,048506,07:52:00,07:52:00,9,Zugló vasútállomás,NaN,NaN,3713.0,472,472
548966,C966101221,048506,16:35:00,16:35:00,9,Zugló vasútállomás,NaN,NaN,3713.0,995,995
...,...,...,...,...,...,...,...,...,...,...,...
5688598,D066221107,048506,03:09:00,03:09:00,42,"Rákospalota, Székely Elek út",NaN,NaN,20957.0,189,189
5688676,D066221115,048506,03:30:00,03:30:00,42,"Rákospalota, Kossuth utca",NaN,NaN,20957.0,210,210
5688727,D066221125,048506,03:50:00,03:50:00,26,NaN,NaN,NaN,13366.0,230,230
5688784,D066221131,048506,04:09:00,04:09:00,42,Újpest-központ M,NaN,NaN,20957.0,249,249
5688841,D066221139,048506,04:29:00,04:29:00,42,Újpest-központ M,NaN,NaN,20957.0,269,269

Látszik, hogy jó sok indulás van ebből a megállóból

## Adatvizsgálat: hogyan lesznek meg a fő megállók?

In [74]:
stop_id = "048506" # Szent István Bazilika
#stop_id = "F01029" # Nyugati
parent_stop_id = df_stops[ df_stops["stop_id"] == stop_id]["parent_station"].iloc[0]
parent_stop_id

nan

In [75]:
if parent_stop_id is not np.nan:
        stop_id = parent_stop_id
stop_name = df_stops[ df_stops["stop_id"] == stop_id]["stop_name"].iloc[0]
stop_name

'Szent István Bazilika'

Itt látszik, hogy ez igy nem lesz OK. Az adatok nem tartalmaznak információt arra, hogy melyik az al, vagy melyik a fő megálló

## Melyik útvonalak állnak meg ebben a megállóban?

In [76]:
df_megallo_jaratok = pd.merge( df_stop_times[ df_stop_times["stop_id"] == stop_id], df_trips, left_on="trip_id", right_on="trip_id").drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,stop_headsign,stop_sequence
0,048506,Szent István Bazilika,4720,Zugló vasútállomás,9
544,048506,Szent István Bazilika,9140,"Káposztásmegyer, Mogyoródi-patak",30
558,048506,Szent István Bazilika,9310,Nyugati pályaudvar M ► Zöldmál,2
581,048506,Szent István Bazilika,9141,Újpest-központ M,12
607,048506,Szent István Bazilika,9500,"Rákospalota, Székely Elek út",42
608,048506,Szent István Bazilika,9501,NaN,42
635,048506,Szent István Bazilika,0090,"Óbuda, Bogdáni út",17

## Sajnos nem világos miért nem lehet két mezőt könnyen selectezni logikai operátorokkal

In [77]:
#df_megallo_jaratok = pd.merge( df_stop_times[ df_stop_times["stop_id"] == stop_id and df_stop_times["arrival_time_min"] > 60*8+15 ] , df_trips, left_on="trip_id", right_on="trip_id").drop_duplicates("route_id")
#df_megallo_jaratok["stop_id"]=stop_id
#df_megallo_jaratok["stop_name"]=stop_name

#df_megallo_jaratok[["stop_id","stop_name","route_id","stop_headsign","stop_sequence"]]

In [78]:
 a = pd.Series(df_stop_times["stop_id"] == stop_id)
 a

0          False
1          False
2          False
3          False
4          False
           ...
5752577    False
5752578    False
5752579    False
5752580    False
5752581    False
Name: stop_id, Length: 5752582, dtype: bool

In [79]:
 b = pd.Series(df_stop_times["arrival_time_min"] > 60*8+15 )
 b

0          False
1          False
2           True
3           True
4           True
           ...
5752577     True
5752578     True
5752579     True
5752580     True
5752581     True
Name: arrival_time_min, Length: 5752582, dtype: bool

In [80]:
a & b

0          False
1          False
2          False
3          False
4          False
           ...
5752577    False
5752578    False
5752579    False
5752580    False
5752581    False
Length: 5752582, dtype: bool

## Melyik járatok állnak meg ebben a megállóban reggel 9:00 körül (1)

In [81]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time.str.startswith("09").values'), df_trips, left_on='trip_id', right_on='trip_id').sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","arrival_time", "arrival_time_min","stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
54,048506,Szent István Bazilika,0090,09:00:00,540,"Óbuda, Bogdáni út",17
18,048506,Szent István Bazilika,4720,09:00:00,540,Zugló vasútállomás,9

## Melyik járatok állnak meg ebben a megállóban reggel 10:00 körül (2)

In [82]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time > "10:00:00"'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
3,048506,Szent István Bazilika,4720,10:01:00,601,Zugló vasútállomás,9
1093,048506,Szent István Bazilika,0090,10:06:00,606,"Óbuda, Bogdáni út",17
401,048506,Szent István Bazilika,9500,24:09:00,1449,"Rákospalota, Székely Elek út",12
486,048506,Szent István Bazilika,9140,24:19:00,1459,"Káposztásmegyer, Mogyoródi-patak",30

## Most inkább nem string-et keresünk, hanem számot
Kétszer olyan gyors lett a futtatás

In [83]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time_min > 60*10'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
3,048506,Szent István Bazilika,4720,10:01:00,601,Zugló vasútállomás,9
1093,048506,Szent István Bazilika,0090,10:06:00,606,"Óbuda, Bogdáni út",17
401,048506,Szent István Bazilika,9500,24:09:00,1449,"Rákospalota, Székely Elek út",12
486,048506,Szent István Bazilika,9140,24:19:00,1459,"Káposztásmegyer, Mogyoródi-patak",30

## Most kiegészítjük az útvonal azonosítóval is (járatszám)

Ez még egy join

In [84]:
df_megallo_jaratok2 = pd.merge( df_megallo_jaratok, df_routes, left_on="route_id", right_on="route_id")
df_megallo_jaratok2[["stop_id","stop_name","route_id","arrival_time", "route_short_name", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,route_short_name,stop_headsign,stop_sequence
0,048506,Szent István Bazilika,4720,10:01:00,72,Zugló vasútállomás,9
1,048506,Szent István Bazilika,0090,10:06:00,9,"Óbuda, Bogdáni út",17
2,048506,Szent István Bazilika,9500,24:09:00,950,"Rákospalota, Székely Elek út",12
3,048506,Szent István Bazilika,9140,24:19:00,914,"Káposztásmegyer, Mogyoródi-patak",30

In [85]:
stop_id = "F00933"
stop_id = "F01029"

parent_stop_id = df_stops[ df_stops["stop_id"] == stop_id]["parent_station"].iloc[0]
parent_stop_id

nan

Melyek azok az állomások amiknek van főmegállója?

# KÖZELI ÁTSZÁLLÁSI PONTOK

Ez úgy tűnik földrajzi koordináták alapján kell megkeresni.

In [86]:

# Create a list of Point objects
points = [Point(xy) for xy in zip(df_stops['stop_lon'], df_stops['stop_lat'])]

# Create a GeoSeries from the list of points with the correct CRS
gs = gpd.GeoSeries(points, crs='EPSG:4326')

gdf_stops = gpd.GeoDataFrame(df_stops, geometry=gs, crs="EPSG:4326")
gdf_stops.head(5)

,stop_id,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding,geometry
0,002133,"Örs vezér tere M+H, déli tárolótér",47.500366,19.135700,002133,NaN,NaN,NaN,NaN,POINT (19.1357 47.50037)
1,002138,Kőbánya alsó vasútállomás,47.483139,19.127891,002138,NaN,NaN,NaN,2.0,POINT (19.12789 47.48314)
2,003002,Puskás Ferenc Stadion M,47.500368,19.103406,003002,NaN,NaN,NaN,NaN,POINT (19.10341 47.50037)
3,004716,"ÉD metró járműtelep,porta",47.469651,19.129090,004716,NaN,NaN,NaN,2.0,POINT (19.12909 47.46965)
4,004948,Metró ÉD járműtelep (kapu),47.465239,19.142612,004948,NaN,NaN,NaN,NaN,POINT (19.14261 47.46524)

Az EPSG:4326 nem jó távolságmérésre, mert nem tudom miért.
De a 3035 az jó, Németországhoz kötött valami. Ezért átmegyek arra:

In [87]:
gdf_stops.to_crs("epsg:3035",inplace=True)
gdf_stops.head(5)

,stop_id,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding,geometry
0,002133,"Örs vezér tere M+H, déli tárolótér",47.500366,19.135700,002133,NaN,NaN,NaN,NaN,POINT (5007781.301 2752100.781)
1,002138,Kőbánya alsó vasútállomás,47.483139,19.127891,002138,NaN,NaN,NaN,2.0,POINT (5007426.257 2750125.866)
2,003002,Puskás Ferenc Stadion M,47.500368,19.103406,003002,NaN,NaN,NaN,NaN,POINT (5005367.638 2751801.574)
3,004716,"ÉD metró járműtelep,porta",47.469651,19.129090,004716,NaN,NaN,NaN,2.0,POINT (5007694.861 2748647.499)
4,004948,Metró ÉD járműtelep (kapu),47.465239,19.142612,004948,NaN,NaN,NaN,NaN,POINT (5008764.678 2748285.946)

Most a Nyugatihoz viszonyítva fogunk közeli megállókat keresni

In [88]:
stop_id = "F01029" # Nyugati
gdf_nyugati = gdf_stops [ gdf_stops["stop_id"] == stop_id ]
gdf_megallo = gdf_nyugati.to_crs(epsg=3035)
gdf_megallo

,stop_id,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding,geometry
2579,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01029,NaN,NaN,NaN,1.0,POINT (5001786.02 2752416.904)

In [89]:
gdf_nearest_stops = gdf_megallo.sjoin_nearest(gdf_stops,distance_col="distance", how="right", exclusive = True, max_distance = 500)
gdf_nearest_stops.columns
#gdf_nearest_stops[["stop_id_left","stop_name_left","stop_lat_left","stop_lon_left","stop_id_right","stop_name_right","stop_lat_right","stop_lon_right","distance"]]

Index(['index_left', 'stop_id_left', 'stop_name_left', 'stop_lat_left',
       'stop_lon_left', 'stop_code_left', 'location_type_left',
       'location_sub_type_left', 'parent_station_left',
       'wheelchair_boarding_left', 'stop_id_right', 'stop_name_right',
       'stop_lat_right', 'stop_lon_right', 'stop_code_right',
       'location_type_right', 'location_sub_type_right',
       'parent_station_right', 'wheelchair_boarding_right', 'geometry',
       'distance'],
      dtype='object')

In [90]:
gdf_nearest_stops.nsmallest(40,'distance')[["stop_id_left","stop_name_left","stop_lat_left","stop_lon_left","stop_id_right","stop_name_right","stop_lat_right","stop_lon_right","distance"]]

,stop_id_left,stop_name_left,stop_lat_left,stop_lon_left,stop_id_right,stop_name_right,stop_lat_right,stop_lon_right,distance
2503,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00935,Nyugati pályaudvar M,47.509922,19.056658,39.253332
6099,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYI,Nyugati pályaudvar [I],47.509870,19.056404,56.669957
2502,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00934,Nyugati pályaudvar M,47.509896,19.056394,57.835671
6095,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYE,Nyugati pályaudvar [E],47.510447,19.056426,89.626772
6098,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYH,Nyugati pályaudvar [H],47.510233,19.056103,91.944253
2501,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00933,Nyugati pályaudvar M,47.510300,19.056167,92.071854
6097,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYG,Nyugati pályaudvar [G],47.510326,19.056196,92.107868
6090,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NY3,Nyugati pályaudvar (lift » M3),47.510040,19.055784,106.075445
129,F01029,Nyugati pályaudvar M,47.509806,19.057151,008137,Nyugati pályaudvar,47.510571,19.056072,117.418620
6096,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYF,Nyugati pályaudvar [F],47.510703,19.056257,120.137919
6088,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NY1,Nyugati pályaudvar,47.510545,19.055967,121.026471
1349,F01029,Nyugati pályaudvar M,47.509806,19.057151,102861,Nyugati pályaudvar M,47.510757,19.056308,123.147823
1395,F01029,Nyugati pályaudvar M,47.509806,19.057151,118346,Nyugati pályaudvar M (Podmaniczky utca),47.509276,19.058597,123.614908
2581,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01031,Nyugati pályaudvar M (Podmaniczky utca),47.509276,19.058597,123.614908
6188,F01029,Nyugati pályaudvar M,47.509806,19.057151,MERGED_F01031,Nyugati pályaudvar M (Podmaniczky utca),47.509276,19.058597,123.614908
2578,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01028,Nyugati pályaudvar M,47.510769,19.056301,124.561703
1639,F01029,Nyugati pályaudvar M,47.509806,19.057151,CSF00936,Nyugati pályaudvar,47.510768,19.056111,132.347975
6094,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYD,Nyugati pályaudvar [D],47.511026,19.057148,135.694557
2580,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01030,Nyugati pályaudvar M (Podmaniczky utca),47.509123,19.058664,136.686791
2577,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01027,Nyugati pályaudvar M,47.511012,19.056487,142.970302
2505,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00937,Nyugati pályaudvar,47.510828,19.055952,144.887681
2576,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01025,Nyugati pályaudvar M,47.510994,19.056288,147.022687
1127,F01029,Nyugati pályaudvar M,47.509806,19.057151,071659,Nyugati pályaudvar M,47.509906,19.055040,159.303033
6100,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYJ,Nyugati pályaudvar [J],47.510011,19.055055,159.378447
6103,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYM,Nyugati pályaudvar [M],47.510917,19.055716,163.833368
2575,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01024,Nyugati pályaudvar M,47.511228,19.056474,165.985563
6101,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYK,Nyugati pályaudvar [K],47.510513,19.055031,177.676246
6093,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYC,Nyugati pályaudvar [C],47.511509,19.056730,191.929523
2574,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01023,Nyugati pályaudvar M,47.511524,19.056686,194.132545
6102,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYL,Nyugati pályaudvar [L],47.510792,19.055004,194.999986
2504,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00936,Nyugati pályaudvar,47.511720,19.056873,213.831208
6089,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NY2,Nyugati pályaudvar,47.511807,19.056937,223.082319
6092,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYB,Nyugati pályaudvar [B],47.512118,19.057114,257.157912
6091,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYA,Nyugati pályaudvar [A],47.512240,19.056584,273.904365
2508,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00940,Báthory utca / Bajcsy-Zsilinszky út,47.507189,19.055730,310.513995
2506,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00938,Báthory utca / Bajcsy-Zsilinszky út,47.507063,19.054270,375.050159
2507,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00939,Báthory utca / Bajcsy-Zsilinszky út,47.506506,19.055716,383.024550
2615,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01068,Ferdinánd híd (Izabella utca),47.510112,19.062341,392.416066
2619,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01072,Ferdinánd híd (Izabella utca),47.511037,19.062659,437.269358
2500,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00932,Szent István körút,47.512046,19.052319,440.165891